language: node_js
node_js:
  - 12

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install
  #- npm install --registry=https://registry.npm.taobao.org

before_script:

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update files"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REP}" master:${GH_BRANCH}

branches:
  only:
    - master
env:
global:
   #- GH_REP: github.com/yimogit/metools.git
